### ISSUE TITLE
Lost purple strip on bottom of header banner 

### ISSUE THREAD

**Issue by Pro-Paul** [NHSLeadership/nightingale-wp#119]
![screen shot 2018-04-25 at 14 02 46](https://user-images.githubusercontent.com/23170050/39247453-5a158498-4891-11e8-9eaa-39cc8a3318d3.png)
As you can see above we have lost the purple strip that should be directly below the blue strip

**Comment by Android63** [comment]
@Pro-Paul this is a Nightingale issue. See https://github.com/NHSLeadership/nightingale/issues/224
