### ISSUE TITLE
Breadcrumb width

### ISSUE THREAD

**Issue by Pro-Paul** [NHSLeadership/nightingale-wp#120]
![screen shot 2018-04-25 at 14 04 17](https://user-images.githubusercontent.com/23170050/39247542-9c08862a-4891-11e8-959a-639464aba964.png)
Breadcrumb margins should be 30 px each side, seems that it is being cut short. please refer to:
https://share.goabstract.com/647598fb-284d-4112-9f75-454609d76b60

**Comment by Android63** [comment]
This is a nightingale issue @Pro-Paul. See https://github.com/NHSLeadership/nightingale/issues/226
