### ISSUE TITLE
Temp remove overlay

### ISSUE THREAD

**Issue by Pro-Paul** [NHSLeadership/nightingale-wp#122]
![screen shot 2018-04-25 at 14 48 32](https://user-images.githubusercontent.com/23170050/39249965-c6c9f384-4897-11e8-8a5a-55cfeab77834.png)
Temporarily remove the purple overlay feature.

**Comment by Android63** [comment]
@Pro-Paul this is built into the Nightingale framework and isn't specific to the Nightingale-WP theme.
