### ISSUE TITLE
Cohort information panels

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale-wp#128]
These show a bit about each cohort with a progress bar indicating how much time is left before the application close date.

Design is as shown below:
![screen shot 2018-05-01 at 13 57 43](https://user-images.githubusercontent.com/1991226/39473632-b2d41a9e-4d47-11e8-8f8c-ce64b2186a4c.png)

**Comment by Android63** [comment]
Marketing and Engagement said that they'd prefer to have manual control over the cohort summary components on the home page and that they don't want bar graphs on them. This issue is on hold pending simplified design from @Pro-Paul

**Comment by Pro-Paul** [comment]
I have asked M+E to sit down and discuss their exact needs, although I still don't think we should be changing the format at this stage.

**Comment by Pro-Paul** [comment]
After having a brief war with James, please find the updated cohort designs on abstract:
https://share.goabstract.com/48c6fe45-4f1c-4e02-99b2-6aef19f7e98f

**Comment by Android63** [comment]
The new design is like this:

![screen shot 2018-05-11 at 15 08 27](https://user-images.githubusercontent.com/1991226/39929748-c066fd3e-5530-11e8-8a29-f1c674b0cc0c.png)

Maybe call them Call to Action cards?
