### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Pro-Paul** [NHSLeadership/nightingale-wp#37]
<img width="336" alt="screen shot 2017-08-17 at 13 09 18" src="https://user-images.githubusercontent.com/23170050/29411558-4c58c91e-834d-11e7-9f56-4a88f95c3f0f.png">

**Comment by Android63** [comment]
I think we need this for the corporate website, right @cehwitham?

**Comment by cehwitham** [comment]
Agreed @Android63 we know have a use case for these.

**Comment by Android63** [comment]
The plan here is to create a "tabbed page" template which admins will be able to use to allow tabbed navigation among all the child pages that (1) belong to a parent page with this template and (2) use this template themselves. So if, for example, a parent page has 10 child pages, but only 6 of them use the tabbed page template, then only those 6 pages will be shown in the tabs.
