### ISSUE TITLE
Header search bar

### ISSUE THREAD

**Issue by Pro-Paul** [NHSLeadership/nightingale-wp#41]
<img width="518" alt="screen shot 2017-08-17 at 13 11 55" src="https://user-images.githubusercontent.com/23170050/29411644-a7f03690-834d-11e7-84d8-dfea10aaa8f2.png">

**Comment by Android63** [comment]
Awaiting https://github.com/NHSLeadership/nightingale/pull/185

**Comment by Android63** [comment]
Since NHSLeadership/nightingale#185 has now been merged, this issue is unblocked.
