### ISSUE TITLE
JavaScript Errors

### ISSUE THREAD

**Issue by Android63** [NHSLeadership/nightingale-wp#96]
As shown below, we're suddenly getting JS errors:

![screen shot 2018-01-30 at 12 08 00](https://user-images.githubusercontent.com/1991226/35565702-85809e2e-05b6-11e8-8d26-489459aa6d5b.png)

It seems to be at least partly due to the element 'jsPage' not being found, but I don't see why this is a problem now when it wasn't before (unless it's gone unnoticed all this time).

Could you take a look with me please @cehwitham?

**Comment by cehwitham** [comment]
Do you still need me to look at this @Android63 ? Looks like you've found a fix?

**Comment by Android63** [comment]
It's OK @cehwitham. As you say, I've already addressed this in https://github.com/NHSLeadership/nightingale-wp/pull/97
